@baseUrl = http://localhost:3001
@contentType = application/json
@baseEndPoint = compliments

### Create a user
POST {{baseUrl}}/{{baseEndPoint}}
Content-Type: {{contentType}}

{
  "message": "",
  "tag_id": "",
  "user_receive": "",
  "user_sender": ""
}
