@baseUrl = http://localhost:3001
@contentType = application/json
@baseEndPoint = login

### Login
POST {{baseUrl}}/{{baseEndPoint}}
Content-Type: {{contentType}}

{
  "email": "beutrano@test.com",
  "password": "123456"
}
