@baseUrl = http://localhost:3001
@contentType = application/json
@baseEndPoint = users

### Get user
GET {{baseUrl}}/{{baseEndPoint}}/30cd9d88-2508-4dba-8ee8-c88d1f1b37ac
Content-Type: {{contentType}}

### List users
GET {{baseUrl}}/{{baseEndPoint}}
Content-Type: {{contentType}}

### Create a user
POST {{baseUrl}}/{{baseEndPoint}}
Content-Type: {{contentType}}

{
  "name": "1sa",
  "email": "1sa@test.com",
  "password": "123456",
  "admin": true
}
