@baseUrl = http://localhost:3001
@contentType = application/json
@baseEndPoint = users

### List users
GET {{baseUrl}}/{{baseEndPoint}}
Content-Type: {{contentType}}

### Create a user
POST {{baseUrl}}/{{baseEndPoint}}
Content-Type: {{contentType}}

{
  "name": "1sa",
  "email": "1sa@test.com",
  "password": "123456",
  "admin": true
}
