@baseUrl = http://localhost:3001
@contentType = application/json
@baseEndPoint = users

### Create a user
POST {{baseUrl}}/{{baseEndPoint}}
Content-Type: {{contentType}}

{
  "name": "fulano",
  "email": "test@test.com"
}
